#Whist save file
#Sun Apr 19 02:52:01 CEST 2026
dealerIndex=0
description=My test save
mode=COUNT
player.0.id=39603eba-df31-4be9-932e-1a27b90e47e0
player.0.name=P1
player.0.score=21
player.0.strategy=HUMAN
player.1.id=67e588f2-f4c1-4392-8e90-4d7a98fe7833
player.1.name=P2
player.1.score=-7
player.1.strategy=HUMAN
player.2.id=780d0b6a-72e7-4a55-bae2-2449a36fe1e4
player.2.name=P3
player.2.score=-7
player.2.strategy=HUMAN
player.3.id=729d6b98-aea2-4e65-a4cd-af7b85c3b669
player.3.name=P4
player.3.score=-7
player.3.strategy=HUMAN
player.count=4
round.0.bidType=SOLO_PROPOSAL
round.0.bidderIndex=0
round.0.miserieWinners.count=0
round.0.multiplier=1
round.0.participants.0=0
round.0.participants.count=1
round.0.scoreDelta.0=21
round.0.scoreDelta.1=-7
round.0.scoreDelta.2=-7
round.0.scoreDelta.3=-7
round.0.tricksWon=10
round.0.trumpSuit=NONE
round.count=1
