#Whist save file
#Sun Apr 19 02:34:01 CEST 2026
dealerIndex=0
description=resumeTestCount
mode=COUNT
player.0.id=c66e4d87-6c52-4399-a074-419bf2b6c5cb
player.0.name=P1
player.0.score=21
player.0.strategy=HUMAN
player.1.id=59059c44-8a3f-4a11-bcc9-3878e3eaa254
player.1.name=P2
player.1.score=-7
player.1.strategy=HUMAN
player.2.id=c4aab0e1-1905-47a5-b5f4-dae58c48aaa0
player.2.name=P3
player.2.score=-7
player.2.strategy=HUMAN
player.3.id=5c2f2e67-8bbc-4689-8f0a-394bc0cdd3ce
player.3.name=P4
player.3.score=-7
player.3.strategy=HUMAN
player.count=4
round.0.bidType=SOLO_PROPOSAL
round.0.bidderIndex=0
round.0.miserieWinners.count=0
round.0.multiplier=1
round.0.participants.0=0
round.0.participants.count=1
round.0.scoreDelta.0=21
round.0.scoreDelta.1=-7
round.0.scoreDelta.2=-7
round.0.scoreDelta.3=-7
round.0.tricksWon=10
round.0.trumpSuit=NONE
round.count=1
