#Whist save file
#Sun Apr 19 02:52:01 CEST 2026
dealerIndex=0
description=validDescription
mode=COUNT
player.0.id=e8d32f5d-31e1-44fa-b44c-a2d58686ddfc
player.0.name=P1
player.0.score=18
player.0.strategy=HUMAN
player.1.id=90e3ecba-7765-4495-953f-8dd4123d8c52
player.1.name=P2
player.1.score=-6
player.1.strategy=HUMAN
player.2.id=065c8d4d-98ec-4296-9272-129abf4de385
player.2.name=P3
player.2.score=-6
player.2.strategy=HUMAN
player.3.id=c794f5a2-f04b-4d0a-b065-f5a2853fd4dc
player.3.name=P4
player.3.score=-6
player.3.strategy=HUMAN
player.count=4
round.0.bidType=SOLO_PROPOSAL
round.0.bidderIndex=0
round.0.miserieWinners.count=0
round.0.multiplier=1
round.0.participants.0=0
round.0.participants.count=1
round.0.scoreDelta.0=18
round.0.scoreDelta.1=-6
round.0.scoreDelta.2=-6
round.0.scoreDelta.3=-6
round.0.tricksWon=9
round.0.trumpSuit=NONE
round.count=1
