package base.domain.events.bidevents;

import base.domain.bid.BidType;
import base.domain.card.Suit;
import base.domain.player.Player;
import base.domain.events.GameEvent;

/**
 * A Data Transfer Object (DTO) representing a player's turn to place a bid.
 * * This event is generated by the BidState and consumed by the IO (TerminalManager/GUI)
 * to provide the user with the necessary context to make a legal bidding decision.
 *
 * @param playerName            The name of the player who is currently prompted to bid.
 * @param dealtTrump            The suit of the card turned up at the start of the deal.
 * @param currentHighestBidType The strongest bid placed so far in this round (null if first bidder).
 * @param bidTypes              The array of all possible BidType options available for selection.
 */
public record BidTurnEvent(String playerName, Suit dealtTrump, BidType currentHighestBidType, BidType[] bidTypes) implements GameEvent {
}
