package base.domain.round;

import base.domain.bid.Bid;
import base.domain.bid.BidCategory;
import base.domain.bid.BidManager;
import base.domain.bid.BidType;
import base.domain.card.Suit;
import base.domain.player.Player;
import base.domain.player.PlayerId;
import base.domain.scores.ScoringRegistry;
import base.domain.trick.Trick;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import static base.domain.round.TrickLedger.MAX_TRICKS;

/**
 * Represents a single Round in a game of Whist.
 * A Round consists of a Bidding phase followed by a Play phase of exactly 13 Tricks.
 * This class acts as the Information Expert for managing turn order, tracking played tricks,
 * resolving the winning team, and correctly delegating score calculation and round completion
 * to specialised domain services.
 * <p>
 * Per-round bid history and player↔bid mapping are delegated to {@link BidManager};
 * {@link Bid} no longer knows about {@link Player}. Round asks the manager
 * for bid-history reasoning (highest bid, bidding team, miserie participants).
 *
 * @author Seppe De Houwer, Tommy Wu
 * @since 24/02/26
 */
public class Round {

    /** The 4 players participating in this round. */
    private final List<Player> players;

    /** The player whose turn it currently is to bid or play a card. */
    private Player currentPlayer;

    /** The record of all completed tricks in this round. */
    private final TrickLedger trickLedger;

    /** Per-round bid history and player↔bid mapping. */
    private final BidManager bidManager;

    private RoundContract roundContract;

    /** The score multiplier for this round. */
    private final int multiplier;

    /** Per-player score delta generated by this round, aligned with players list order. */
    private final List<Integer> scoreDeltas;

    /** Tricks won value used in count-mode snapshots, -1 when not applicable. */
    private int countTricksWon;

    /** Winners used in count-mode miserie snapshots. */
    private List<Player> miserieWinners;

    /** Explicit terminal flag used for restored / count rounds without full trick history. */
    private boolean finished;

    // Domain services – stateless, created once.
//    private final RoundScoringService scoringService;
//    private final RoundCompletionService completionService;
//    private final RoundRestorationService restorationService;

    /**
     * Constructs a new Round of Whist.
     *
     * @param players        a list of exactly four players.
     * @param startingPlayer the player who leads the first trick (or first bid).
     * @param multiplier     the score multiplier for this round (e.g., 2 if all PASS last round).
     * @throws IllegalArgumentException if players is null or not containing exactly 4 players.
     * @throws IllegalArgumentException if startingPlayer is null or not in the players list.
     */
    public Round(List<Player> players, Player startingPlayer, int multiplier) {
        if (players == null || players.size() != 4) {
            throw new IllegalArgumentException("Players list must contain exactly 4 players.");
        }
        if (startingPlayer == null || !players.contains(startingPlayer)) {
            throw new IllegalArgumentException("Starting Player must not be null and must be in the players list.");
        }
        this.players = new ArrayList<>(players);
        this.currentPlayer = startingPlayer;
        this.trickLedger = new TrickLedger();
        this.bidManager = new BidManager(this.players);
        this.roundContract = null;
        this.multiplier = multiplier;
        this.scoreDeltas = new ArrayList<>(List.of(0, 0, 0, 0));
        this.countTricksWon = -1;
        this.miserieWinners = new ArrayList<>();
        this.finished = false;
        this.scoringService = new RoundScoringService();
        this.completionService = new RoundCompletionService();
        this.restorationService = new RoundRestorationService();
    }

    // =========================================================================
    // Phase transitions
    // =========================================================================

    /**
     * Finalises the bidding phase and prepares the round for the playing phase.
     * The {@link BidManager} was already populated by {@code BidState}; the
     * {@code finalBids} parameter is kept as a sanity check — we trust the manager
     * as the source of truth.
     *
     * @param finalBids   the complete list of bids made this round.
     * @param highestBid  the winning contract.
     * @param trumpSuit   the active trump suit for the play phase.
     * @param firstPlayer the player who gets to lead the first trick.
     * @throws IllegalArgumentException if any argument is invalid.
     * @throws IllegalStateException    if the BidManager is out of sync with {@code finalBids}.
     */
    public void startPlayPhase(List<Bid> finalBids, Bid highestBid, Suit trumpSuit, Player firstPlayer) {
        if (finalBids == null || finalBids.size() != this.players.size()) {
            throw new IllegalArgumentException("Must have exactly 4 final bids.");
        }
        if (highestBid == null) {
            throw new IllegalArgumentException("Cannot start play phase without a winning bid.");
        }
        if (firstPlayer == null) {
            throw new IllegalArgumentException("Cannot start play phase without a first player.");
        }
        if (bidManager.getAllBids().size() != this.players.size()) {
            throw new IllegalStateException("BidManager state out of sync with provided finalBids.");
        }
        Set<PlayerId> biddingTeam = new HashSet<>(bidManager.resolveBiddingTeam());
        Set<PlayerId> defendingTeam = new HashSet<>(this.players.stream().map(Player::getId).toList());
        defendingTeam.removeAll(biddingTeam);

        this.roundContract = new RoundContract(highestBid, trumpSuit, biddingTeam, defendingTeam ,multiplier);

        this.currentPlayer = firstPlayer;
    }

    /**
     * Aborts the round because all players passed.
     * The {@link BidManager} already holds the 4 PASS bids (placed by BidState);
     * we only need to record the all-PASS marker on Round itself for the
     * multiplier carry-over.
     *
     * @param finalBids the 4 pass bids.
     * @throws IllegalArgumentException if finalBids is null, not exactly 4, or not all PASS.
     */
    public void abortWithAllPass(List<Bid> finalBids) {
        if (finalBids == null) {
            throw new IllegalArgumentException("finalBids must not be null.");
        }
        if (finalBids.size() != this.players.size()) {
            throw new IllegalArgumentException("Must have exactly 4 final bids.");
        }
        if (!finalBids.stream().allMatch(bid -> bid.getType() == BidType.PASS)) {
            throw new IllegalArgumentException("All bids must be PASS.");
        }
        this.players.forEach(Player::flushHand);
        this.finished = true;
    }

    /**
     * Advances the {@code currentPlayer} to the next player in turn order.
     */
    public void advanceToNextPlayer() {
        int currentIdx = players.indexOf(currentPlayer);
        this.currentPlayer = players.get((currentIdx + 1) % 4);
    }

    /**
     * Registers a completed Trick to this Round's history.
     * The winner of the trick becomes the next current player.
     * If the round should finish automatically (13 tricks played or Miserie early
     * termination), scores are calculated and the round is marked finished.
     *
     * @param trick the completed trick to be added.
     * @throws IllegalArgumentException if the trick is null or incomplete.
     * @throws IllegalStateException    if the round is already finished.
     */
    public void finalizeTrick(Trick trick) {
        if (this.finished) {
            throw new IllegalStateException("Cannot add trick to finished round");
        }
        this.trickLedger.recordTrick(trick);
        this.currentPlayer = getPlayerById(trick.getWinningPlayerId());

        if (completionService.shouldAutoFinish(this)) {
            this.finished = true;
            scoringService.calculateScores(this);
        }
    }

    // =========================================================================
    // Scoring
    // =========================================================================

    /**
     * Manually triggers score calculation. For normal play this is done
     * automatically by {@link #finalizeTrick(Trick)} when the round completes.
     */
    public void calculateScores() {
        scoringService.calculateScores(this);
    }

    /**
     * Determines which players won the round based on the final trick count
     * and the highest bid.
     *
     * @return a list of winning players, or an empty list if the round is not yet finished.
     * @throws IllegalStateException if highestBid is null while the round is finished.
     */
    public List<Player> getWinningPlayers() {
        if (!isFinished()) {
            return new ArrayList<>();
        }
        if (highestBid == null) {
            throw new IllegalStateException("Cannot calculate winners: highestBid is null.");
        }

        List<Player> bidders = getBiddingTeamPlayers();

        if (highestBid.getType().getCategory() == BidCategory.MISERIE) {
            if (this.trickLedger.isFull()) {
                return List.copyOf(miserieWinners);
            }
            List<Player> successful = new ArrayList<>();
            for (Player p : bidders) {
                if (getTricksWonBy(List.of(p)) == 0) {
                    successful.add(p);
                }
            }
            return successful;
        }

        int tricksWon = countTricksWon >= 0 ? countTricksWon : getTricksWonBy(bidders);
        int points = highestBid.calculateBasePoints(tricksWon);

        if (points > 0) {
            return bidders;
        }

        List<Player> defenders = new ArrayList<>(this.players);
        defenders.removeAll(bidders);
        return defenders;
    }

    /**
     * Maps a {@link PlayerId} to the actual {@link Player} object.
     *
     * @param id the player's id.
     * @return the player.
     * @throws IllegalStateException if no player with the given id is found.
     */
    public Player getPlayerById(PlayerId id) {
        return players.stream()
                .filter(p -> p.getId().equals(id))
                .findFirst()
                .orElseThrow(() -> new IllegalStateException("PlayerId not found!"));
    }

    /**
     * Counts how many tricks were won by the given list of players.
     *
     * @param team list of players.
     * @return number of tricks won by the team.
     */
    public int getTricksWonBy(List<Player> team) {
        return this.trickLedger.getTricksWonByTeam(team);
    }

    // =========================================================================
    // Accessors
    // =========================================================================

    /**
     * The per-round BidManager. Used by BidState during bidding and by callers
     * that need to ask "who placed this bid?" (e.g. PlayState, persistence,
     * domain services).
     */
    public BidManager getBidManager() {
        return bidManager;
    }

    public List<Player> getPlayers() {
        return List.copyOf(players);
    }

    public Player getCurrentPlayer() {
        return currentPlayer;
    }

    /** All bids placed during this round, in placement order. Delegates to {@link BidManager}. */
    public List<Bid> getBids() {
        return bidManager.getAllBids();
    }

    public List<Player> getBiddingTeamPlayers() {
        return List.copyOf(biddingTeam);
    }

    public Bid getHighestBid() {
        return highestBid;
    }

    public Suit getTrumpSuit() {
        return trumpSuit;
    }

    public int getMultiplier() {
        return multiplier;
    }

    public List<Integer> getScoreDeltas() {
        return List.copyOf(scoreDeltas);
    }

    public int getCountTricksWon() {
        return countTricksWon;
    }

    public int getBiddingTeamTricksWon() {
        if (biddingTeam.isEmpty()) {
            return -1;
        }
        return getTricksWonBy(biddingTeam);
    }

    public List<Player> getCountMiserieWinners() {
        return List.copyOf(miserieWinners);
    }

    public List<Trick> getTricks() {
        return this.trickLedger.getTricks();
    }

    public Trick getLastPlayedTrick() {
        return this.trickLedger.getLastTrick();
    }


    // =========================================================================
    // Setters used for count-mode or restoration
    // =========================================================================

    /**
     * Atomically resolves a round created via manual count-mode,
     * enforcing that all required state is provided at once.
     */
    public void resolveManualCount(Bid highestBid, List<Player> biddingTeam, int tricksWon, List<Player> miserieWinners) {
        if (highestBid == null || biddingTeam == null || miserieWinners == null) {
            throw new IllegalArgumentException("Cannot resolve manual count with incomplete data");
        }


        this.highestBid = highestBid;
        this.biddingTeam.clear();
        this.biddingTeam.addAll(biddingTeam);
        this.countTricksWon = tricksWon;
        this.miserieWinners = new ArrayList<>(miserieWinners);

        // The Round immediately acts on the new data, acting as the Controller/Expert
        this.finished = true;
        this.calculateScores();
    }

    // =========================================================================
    // Snapshot restore
    // =========================================================================

    /**
     * Rehydrates a historical round from a persisted snapshot without
     * re-running scoring logic.
     * <p>
     * NOTE: {@code GamePersistenceService} is responsible for repopulating the
     * {@link BidManager} via {@code bidManager.placeBid(...)} for the snapshot's
     * bidder before this method runs.
     *
     * @param highestBid          restored winning bid.
     * @param trumpSuit           restored trump suit (can be null for no-trump).
     * @param participants        restored bidding team members.
     * @param tricksWon           restored count-mode tricks won value.
     * @param miserieWinners      restored count-mode miserie winners.
     * @param restoredScoreDeltas restored per-player score deltas.
     */
    public void restoreFromSnapshot(
            Bid highestBid,
            Suit trumpSuit,
            List<Player> participants,
            int tricksWon,
            List<Player> miserieWinners,
            List<Integer> restoredScoreDeltas) {

        this.restoreState(
                highestBid,
                trumpSuit,
                participants,
                tricksWon,
                miserieWinners,
                restoredScoreDeltas);
    }

    // =========================================================================
    // Package-private hooks for domain services
    // =========================================================================

    /** Returns the terminal flag without any logical checks. */
    boolean isMarkedFinished() {
        return finished;
    }

    /** Sets the terminal flag to {@code true}. */
    void markFinished() {
        this.finished = true;
    }

    /** Adds a score delta for the player at the given index. */
    void addScoreDelta(int index, int delta) {
        scoreDeltas.set(index, scoreDeltas.get(index) + delta);
    }

    /**
     * Fully restores the round state from external data (used by restoration service).
     */
    void restoreState(
            Bid highestBid,
            Suit trumpSuit,
            List<Player> participants,
            int tricksWon,
            List<Player> miserieWinners,
            List<Integer> restoredScoreDeltas) {

        this.highestBid = highestBid;
        this.trumpSuit = trumpSuit;
        this.biddingTeam.clear();
        this.biddingTeam.addAll(participants);
        this.countTricksWon = tricksWon;
        this.miserieWinners = miserieWinners == null ? new ArrayList<>() : new ArrayList<>(miserieWinners);

        // Apply score deltas to players and update internal list.
        for (int i = 0; i < this.players.size(); i++) {
            int delta = restoredScoreDeltas.get(i);
            this.players.get(i).updateScore(delta);
            this.scoreDeltas.set(i, delta);
        }

        this.finished = true;
    }

    // =========================================================================
    // Private helpers
    // =========================================================================

    /**
     * Checks whether the given round is finished according to the game rules.
     *
     * @param round the round to evaluate.
     * @return {@code true} if the round is finished.
     */
    public boolean isFinished() {
        if (this.isMarkedFinished()) {
            return true;
        }
        return isAllPassFinished() || shouldAutoFinish();
    }

    /**
     * Determines if the round should automatically finish after a trick is played.
     * This is used by the round itself to trigger automatic scoring.
     *
     * @return {@code true} if the round conditions warrant an automatic end.
     */
    public boolean shouldAutoFinish() {
        if (this.getTricks().size() >= MAX_TRICKS) {
            return true;
        }

        Bid highestBid = this.getHighestBid();
        if (highestBid != null && highestBid.getType().getCategory() == BidCategory.MISERIE) {
            return isMiserieEarlyTermination();
        }
        return false;
    }

    private boolean isAllPassFinished() {
        Bid highestBid = this.getHighestBid();
        return highestBid != null
                && highestBid.getType() == BidType.PASS
                && this.getBids().size() == this.getPlayers().size();
    }

    /**
     * Miserie rounds end early when every Miserie bidder
     * has already failed by taking at least one trick.
     * <p>
     * Participants are resolved via the round's
     * {@link base.domain.bid.BidManager} rather than by inspecting individual
     * {@link Bid} objects, which no longer reference {@link PlayerId}.
     */
    private boolean isMiserieEarlyTermination() {
        Bid highestBid = this.getHighestBid();
        if (highestBid == null || highestBid.getType().getCategory() != BidCategory.MISERIE) {
            return false;
        }

        List<PlayerId> miserieBidders =
                this.getBidManager().findMiserieParticipants(highestBid.getType());

        if (miserieBidders.isEmpty()) {
            return false;
        }

        for (PlayerId bidderId : miserieBidders) {
            boolean wonATrick = this.getTricks().stream()
                    .anyMatch(trick -> trick.getWinningPlayerId().equals(bidderId));
            if (!wonATrick) {
                return false;   // someone is still safe
            }
        }
        return true;            // all Miserie bidders have failed
    }

    /**
     * Retroactively recalculates this round's scores based on updated global rules.
     */
    public void recalculateRetroactiveScores(ScoringRegistry registry) {
        for (int i = 0; i < scoreDeltas.size(); i++) {
            scoreDeltas.set(i, 0);
        }

        scoringService.calculateScores(this, registry);
    }
}